---
name: test
on:
  push:
    tags:
      - v*.*.*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: get deps
        run: go get -d ./...

      - name: release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
